INSERT INTO status (name) VALUES ('В наличии');
INSERT INTO status (name) VALUES ('Нет в наличии');
INSERT INTO category (name) VALUES ('Стиральная машина');
INSERT INTO category (name) VALUES ('Холодильник');
INSERT INTO category (name) VALUES ('Микроволновая печь');
INSERT INTO category (name) VALUES ('Пылесос');
INSERT INTO category (name) VALUES ('Посудомоечная машина');
INSERT INTO category (name) VALUES ('Утюг');
INSERT INTO category (name) VALUES ('Кондиционер');
INSERT INTO color (name) VALUES ('Черный');
INSERT INTO color (name) VALUES ('Белый');
INSERT INTO color (name) VALUES ('Серебристый');
INSERT INTO color (name) VALUES ('Серый');
INSERT INTO color (name) VALUES ('Голубой');
INSERT INTO color (name) VALUES ('Синий');
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('DEXP', 'WM-F610NTMA/WW', 17999, 2, 1, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('LG', 'F2J3NS1W', 38999, 2, 1, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Indesit', 'IWSD 51051 CIS', 20999, 2, 1, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Samsung', 'WW60J42E0HS/LD', 44999, 3, 1, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Aceline', 'B16AMG', 16599, 2, 2, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('DEXP', 'B2-0270AMG', 28999, 1, 2, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Indesit', 'ITS 4180 W', 37999, 2, 2, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('LG', 'GA-B509CQTL', 58999, 2, 2, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('DEXP', 'MS-71', 4999, 1, 3, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Gorenje', 'MO17E1S', 4999, 3, 3, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('LG', 'MS2042DY', 10999, 2, 3, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Samsung', 'MS23J5133AT/BW', 13199, 3, 3, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Thomas', 'DryBox Amfibia', 35599, 1, 4, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Samsung', 'SC4581', 6999, 1, 4, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Polaris', 'PVC 2004RI', 10199, 5, 4, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('DEXP', 'V-2200VC', 4899, 4, 4, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('DEXP', 'M9C7PD', 17999, 2, 5, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Gorenje', 'GS541D10W', 32999, 2, 5, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Samsung', 'DW50R4050FS/WT', 43799, 3, 5, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Midea', 'MFD45S370Wi', 31799, 2, 5, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Tefal', 'Puregliss FV8043E0', 8499, 2, 6, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Polaris', 'PIR 2820AK 3m', 4399, 2, 6, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Philips', 'Azur GC4556/20', 10499, 6, 6, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Braun', 'SI3055BK', 5499, 1, 6, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('TCL', 'TAC-12CHSA/TPG-W', 22999, 2, 7, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('DEXP', 'AC-CX9ONF', 16999, 2, 7, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Electrolux', 'EACS/I-12HAT/N3_21Y', 49499, 2, 7, 1);
INSERT INTO product (brand, model,  price, color_id, category_id, status_id) VALUES ('Centek', 'CT-65FDC12', 32299, 2, 7, 1);
INSERT INTO users (surname, name, patronymic, avatar, login, password, role) VALUES ('Юзеров', 'Юзер', 'Юзерович', 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png', 'user', '$2a$10$DrgZoEa1GEiwjV299yaXzOWj.6scMj8JieWhrLWCbxe0CPR91JmJi', 'USER');
INSERT INTO users (surname, name, patronymic, avatar, login, password, role) VALUES ('Админов', 'Админ', 'Админович', 'https://icons.veryicon.com/png/o/miscellaneous/yuanql/icon-admin.png', 'admin', '$2a$10$DrgZoEa1GEiwjV299yaXzOWj.6scMj8JieWhrLWCbxe0CPR91JmJi', 'ADMIN');
