INSERT INTO status (name) VALUES ('В наличии');
INSERT INTO status (name) VALUES ('Нет в наличии');
INSERT INTO category (name) VALUES ('Стиральная машина');
INSERT INTO category (name) VALUES ('Холодильник');
INSERT INTO category (name) VALUES ('Микроволновая печь');
INSERT INTO category (name) VALUES ('Пылесос');
INSERT INTO category (name) VALUES ('Посудомоечная машина');
INSERT INTO category (name) VALUES ('Утюг');
INSERT INTO category (name) VALUES ('Кондиционер');
INSERT INTO product (brand, price, category_id, status_id) VALUES ('DEXP', 28999, 1, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('LG', 36999, 1, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Indesit', 19699, 1, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Samsung', 31999, 1, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Aceline', 17299, 2, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('DEXP', 24799, 2, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Indesit', 31999, 2, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('LG', 66999, 2, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('DEXP', 4999, 3, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Gorenje', 3999, 3, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('LG', 10699, 3, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Samsung', 14399, 3, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Thomas', 35599, 4, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Samsung', 6999, 4, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Polaris', 11999, 4, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('DEXP', 4899, 4, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('DEXP', 18899, 5, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Gorenje', 32999, 5, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Samsung', 41999, 5, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Midea', 31799, 5, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Tefal', 8499, 6, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Polaris', 3999, 6, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Philips', 4299, 6, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Braun', 5499, 6, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('TCL', 25899, 7, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('DEXP', 14999, 7, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Electrolux', 49499, 7, 1);
INSERT INTO product (brand, price, category_id, status_id) VALUES ('Centek', 29999, 7, 1);
INSERT INTO users (login, password, role) VALUES ('user', '$2a$10$DrgZoEa1GEiwjV299yaXzOWj.6scMj8JieWhrLWCbxe0CPR91JmJi', 'USER');
INSERT INTO users (login, password, role) VALUES ('admin', '$2a$10$DrgZoEa1GEiwjV299yaXzOWj.6scMj8JieWhrLWCbxe0CPR91JmJi', 'ADMIN');
